language: php

addons:
    sonarqube: true
    apt:
        packages:
            - oracle-java8-installer

env:
    global:
        - JAVA_HOME=/usr/lib/jvm/java-8-oracle

php:
    - 7
    - nightly

install:
    - composer install --no-interaction

script:
    - composer test
    - sonar-scanner -Dsonar.login=$sonarlogin
