language: php

addons:
    sonarqube: true

php:
    - 5.6
    - 7
    - hhvm
    - nightly

install:
    - composer install --no-interaction

script:
    - composer test
    - sonar-scanner -Dsonar.login=$sonarlogin
