language: php
jdk:
  - oraclejdk8
php:
  - 5.6
  - 7
  - hhvm
  - nightly
install:
  - composer install --no-interaction
script:
  - composer test
  - ./vendor/joshavg/sonar-runner/bin/sonar-scanner -Dsonar.login=$sonarlogin
