<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Attribute;
use AppBundle\Entity\Schema;
use Doctrine\ORM\EntityRepository;

/**
 * AttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributeRepository extends EntityRepository
{

    /**
     * @param Schema $schema
     * @return Attribute[]
     */
    public function findFromSchema(Schema $schema)
    {
        return $this->findBy([
            'schema' => $schema
        ], [
            'name' => 'ASC'
        ]);
    }

}
