<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Instance;
use AppBundle\Entity\Property;
use Doctrine\ORM\EntityRepository;

/**
 * PropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyRepository extends EntityRepository
{

    /**
     * @param Instance $instance
     * @return Property[]
     */
    public function findFromInstance(Instance $instance)
    {
        return $this->createQueryBuilder('p')
            ->join('p.attribute', 'a')
            ->where('p.instance = :i')
            ->orderBy('a.name')
            ->getQuery()
            ->execute([
                'i' => $instance
            ]);
    }

}
