<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Schema;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * SchemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchemaRepository extends EntityRepository
{

    /**
     * @param User $user
     * @return Schema[]
     */
    public function findFromUser(User $user)
    {
        return $this->findBy([
            'createdBy' => $user
        ], [
            'name' => 'ASC'
        ]);
    }

}
