default_language:
  path: "/"
  defaults:
    _controller: FrameworkBundle:Redirect:redirect
    route: index
    permanent: true
    _locale: "%locale%"


app:
  resource: "@AppBundle/Controller/"
  type: annotation
  prefix: "/{_locale}"
  requirements:
    _locale: "|en|pt-br|toki-pona"
