CREATE CONSTRAINT ON (n:property) ASSERT n.uid IS UNIQUE;
CREATE CONSTRAINT ON (n:instance) ASSERT n.uid IS UNIQUE;
CREATE CONSTRAINT ON (n:attribute) ASSERT n.uid IS UNIQUE;
CREATE CONSTRAINT ON (n:schema) ASSERT n.uid IS UNIQUE;
CREATE CONSTRAINT ON (n:user) ASSERT n.name IS UNIQUE;
