services:

  factory.instance_form:
    class: AppBundle\Form\InstanceFormFactory
    autowire: true

  factory.instance:
    class: AppBundle\Architecture\InstanceFactory
    autowire: true

  factory.date:
    class: AppBundle\Entity\Repository\DateFactory
