services:

  repo.user:
    class: AppBundle\Entity\Repository\UserRepository
    autowire: true

  repo.schema:
    class: AppBundle\Entity\Repository\SchemaRepository
    autowire: true

  repo.attribute:
    class: AppBundle\Entity\Repository\AttributeRepository
    autowire: true

  repo.instance:
    class: AppBundle\Entity\Repository\InstanceRepository
    autowire: true

  repo.relationship:
    class: AppBundle\Entity\Repository\RelationshipRepository
    autowire: true
