services:

  password_hash_encoder:
    class: AppBundle\Architecture\PasswordEncoder

  repo.user:
    class: AppBundle\Entity\Repository\UserRepository
    arguments:
      - "@neo4j.client"

  repo.schema:
    class: AppBundle\Entity\Repository\SchemaRepository
    arguments:
      - "@neo4j.client"
      - "@security.token_storage"
      - "@factory.date"

  repo.attribute:
    class: AppBundle\Entity\Repository\AttributeRepository
    arguments:
      - "@neo4j.client"
      - "@security.token_storage"
      - "@factory.date"

  repo.instance:
    class: AppBundle\Entity\Repository\InstanceRepository
    arguments:
      - "@neo4j.client"
      - "@security.token_storage"
      - "@repo.attribute"
      - "@factory.date"

  repo.relationship:
    class: AppBundle\Entity\Repository\RelationshipRepository
    arguments:
      - "@neo4j.client"
      - "@repo.instance"
      - "@factory.date"

  factory.instance_form:
    class: AppBundle\Form\InstanceFormFactory
    arguments:
      - "@form.factory"
      - "@factory.instance"
      - "@repo.attribute"

  factory.instance:
    class: AppBundle\Architecture\InstanceFactory
    arguments:
      - "@repo.schema"
      - "@repo.attribute"
      - "@factory.date"

  factory.date:
    class: AppBundle\Entity\Repository\DateFactory

  validator.schemaname:
    class: AppBundle\Validator\Constraints\SchemaNameValidator
    arguments:
      - "@repo.schema"
    tags:
      - { name: validator.constraint_validator, alias: validator.schemaname }

  validator.attributename:
    class: AppBundle\Validator\Constraints\AttributeNameValidator
    arguments:
      - "@repo.attribute"
    tags:
      - { name: validator.constraint_validator, alias: validator.attributename }

  filter.formatter.property.value:
    class: AppBundle\Architecture\PropertyValueFormatter
    arguments:
      - "@translator.default"
    tags:
      - name: twig.extension
