services:
      
  password_hash_encoder:
    class: AppBundle\Architecture\PasswordEncoder
  
  repo.user:
    class: AppBundle\Entity\UserRepository
    arguments:
      - "@neo4j.client"
  
  repo.schema:
    class: AppBundle\Entity\SchemaRepository
    arguments:
      - "@neo4j.client"

  appbundle.form.type.NewSchemaType:
    class: AppBundle\Form\NewSchemaType
    arguments:
      - "@router"
      - schema_insert
    tags:
      - { name: form.type, alias: NewSchema }