services:
      
  password_hash_encoder:
    class: AppBundle\Architecture\PasswordEncoder
  
  user.repo:
    class: AppBundle\Entity\UserRepository
    calls:
      - [ setClient, [ "@neo4j.client" ] ]

  appbundle.form.type.NewSchemaType:
    class: AppBundle\Form\NewSchemaType
    arguments:
      - "@router"
      - settings_index
    tags:
      - { name: form.type, alias: NewSchema }