imports:
  - resource: repositories.yml
  - resource: validators.yml
  - resource: transformers.yml
  - resource: factories.yml

services:

  password_hash_encoder:
    class: AppBundle\Architecture\PasswordEncoder

  filter.formatter.property.value:
    class: AppBundle\Architecture\PropertyValueFormatter
    autowire: true
    tags:
      - name: twig.extension

  handler.flashbag:
    class: AppBundle\Architecture\FlashbagHandler
    autowire: true
