services:

  password_hash_encoder:
    class: AppBundle\Architecture\PasswordEncoder

  repo.user:
    class: AppBundle\Entity\UserRepository
    arguments:
      - "@neo4j.client"

  repo.schema:
    class: AppBundle\Entity\SchemaRepository
    arguments:
      - "@neo4j.client"
      - "@security.token_storage"

  repo.attribute:
    class: AppBundle\Entity\AttributeRepository
    arguments:
      - "@neo4j.client"
      - "@security.token_storage"

  form.schema.filter:
    class: AppBundle\Form\Type\SchemaFilterType
    arguments:
      - "@repo.schema"
    tags:
      - { name: form.type }

  validator.schemaname:
    class: AppBundle\Validator\Constraints\SchemaNameValidator
    arguments:
      - "@repo.schema"
    tags:
      - { name: validator.constraint_validator, alias: validator.schemaname }
