services:
  neo4j.client:
    class: laniger\Neo4jBundle\Architecture\Neo4jClientWrapper
    arguments:
      - "%laniger.neo4j.host%"
      - "%laniger.neo4j.port%"
    calls:
      - [ configure, [ "%laniger.neo4j.user%", "%laniger.neo4j.pw%"] ]
      
  neo4j.userprovider:
    class: laniger\Neo4jBundle\Architecture\Neo4jUserProvider
    arguments:
      - "@neo4j.client"