services:
  neo4j.client:
    class: laniger\Neo4jBundle\Architecture\Neo4jClientWrapper
    arguments:
      - "%laniger.neo4j.host%"
      - "%laniger.neo4j.port%"
    calls:
      - [ configure, [ "%laniger.neo4j.user%", "%laniger.neo4j.pw%"] ]
      
  neo4j.userprovider:
    class: laniger\Neo4jBundle\Architecture\Neo4jUserProvider
    arguments:
      - "@neo4j.client"
      
  neo4j.validator.uniquelabel:
    class: laniger\Neo4jBundle\Validator\Constraints\Neo4jUniqueLabelConstraintValidator
    tags:
      - { name: validator.constraint_validator, alias: neo4j.validator.uniquelabel }
    calls:
      - [ setClient, [ "@neo4j.client" ] ]
  
  neo4j.validator.label:
    class: laniger\Neo4jBundle\Validator\Constraints\Neo4jLabelConstraintValidator
    tags:
      - { name: validator.constraint_validator, alias: neo4j.validator.label }